### ISSUE TITLE
Fehlerhafte Generierung von drei aufeinander folgenden Ziffern

### ISSUE THREAD

**Issue by submitnine** [nikolassv/steuerid-generator#1]
Hi,

vielen Dank für dein Code. Dies hat mir sehr geholfen selber einen validator zu schreiben.
Ich habe dein Code genommen und mir 100 Testdaten generiert. Leider wurden auch einige wenige ungültige Nummern generiert.
Beispiele:

98705322218
79043332563
98881352041

Sollte eine Ziffer 3x vorhanden sein, so darf diese nicht hintereinander vorkommen, siehe: https://www.zfa.deutsche-rentenversicherung-bund.de/de/Inhalt/public/4_ID/47_Pruefziffernberechnung/001_Pruefziffernberechnung.pdf . Hier im PDF auf der 4. Seite Punkt 6 "Existieren drei gleiche Ziffern an den Positionen 1 bis 10, dürfen diese gleichen Ziffern niemals an direkt aufeinander folgenden Stellen stehen."

**Comment by nikolassv** [comment]
Vielen Dank für den Hinweis! Das werde ich korrigierten.

**Comment by nikolassv** [comment]
Ich habe den Fehler mit Commit [e27d358](https://github.com/nikolassv/steuerid-generator/commit/e27d358a28a9c5157cb5df35decc4b098b2a858d) behoben
